### ISSUE TITLE
Ruby Capstone Project: Set up Kanban Board

### ISSUE THREAD

**Issue by meryemsanem** [LDouglasOT/Ruby-capstone#36]
Hello 😄 
Here is the [link](https://github.com/LDouglasOT/Ruby-capstone/projects/1) for the GitHub project.

We are 3 people in our group. We created [tasks from here](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md) and assigned each task equally to team members.

Team Member#1 : [Meryem](https://github.com/meryemsanem)
Team Member#2 : [Afreen](https://github.com/tajulafreen)
Team Member#3 : [Luzinda](https://github.com/LDouglasOT)

Thanks for the review.

**Comment by gemmen29** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 💯 
- Descriptive info✔️ 

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Required Changes ♻️
- ### Kindly add a description for the following task:
   - [ ] https://github.com/LDouglasOT/Ruby-capstone/issues/33
   - [ ] https://github.com/LDouglasOT/Ruby-capstone/issues/34
   - [ ] https://github.com/LDouglasOT/Ruby-capstone/issues/35

as per this [requirement](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/setup_kanban_board.md#:~:text=Has%20a%20description%20of%20the%20task.). All tasks should have a description.

- ### Kindly add a number of points for the following tasks:
   - [ ] https://github.com/LDouglasOT/Ruby-capstone/issues/33
   - [ ] https://github.com/LDouglasOT/Ruby-capstone/issues/15
   - [ ] https://github.com/LDouglasOT/Ruby-capstone/issues/17

as per this [requirement](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/setup_kanban_board.md#:~:text=Has%20the%20number%20of%20points%20in%20the%20%5BXpt%5D%20prefix). All tasks should have a number of points.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by divinecharlotte** [comment]
# Hello @Team    😃 🥳 🎉 🎈 

Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say other than... it's time to merge it 👍🏻 ✅ 
### To Highlight 💯

- Good implementation of the required changes ✔️
- Descriptive issue✔️






## Congratulations! 🎉 

<img src="https://media3.giphy.com/media/3KC2jD2QcBOSc/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
